Month8/step1
SergeyKukhtalevV/react-burger pull request #3
Opened 2022-12-31 18:47 UTC by SergeyKukhtalevV

Прошу проверить!
С наступающим Новым Годом!

2022-12-31 20:13 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы успешно добавили в ваш проект контекст, корректно организовали с ним взаимодействие, однако для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**.

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличных праздников!** 🐈

2022-12-31 20:13 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    getOrder();
🔴 **Нужно исправить:**

Не следует отправлять заказ сразу при открытии страницы, отправка должна происходить только по нажатию кнопки "Оформить заказ"

2022-12-31 20:13 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        authorization: 'c362a370-694e-40e1-b195-d72fbbfd69f7',
🔴 **Нужно исправить:**

На данном этапе проекта отсутствует авторизация, поэтому хедер указывать не следует

2022-12-31 20:13 UTC, randomroot commented on src/components/app/app.tsx
> +const urlApi = 'https://norma.nomoreparties.space/api/ingredients';
🔴 **Нужно исправить:**

Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2022-12-31 20:13 UTC, randomroot commented on src/components/app/app.tsx
> +  //const [ingredientsInfo, setIngredientsInfo] = useState({});
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2022-12-31 20:13 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    orderData: {},
🟡 **Можно улучшить:**

В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`

2022-12-31 20:13 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +            className="text text_type_digits-medium">{state.reduce((total, i) => total + i.price, 0) + bun[0].price * 2}</p>
🟡 **Можно улучшить:**

Можно перенести `bun[0].price * 2` в начальное значение функции `reduce`

2022-12-31 20:13 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +          setOrderNumber(order.orderData.order.number)
🔴 **Нужно исправить:**

В модальном окне отображается неправильный номер заказа, т.к. он устанавливается раньше, чем выполнится запрос. Рекомендуется использовать ключевое слово `await` и возвращать из функции номер заказа (см. https://disk.yandex.ru/i/7wtTOEdErvhq3g)

2023-01-10 18:49 UTC, SergeyKukhtalevV commented on src/components/burger-constructor/burger-constructor.jsx
> +    getOrder();
Готово

2023-01-10 19:00 UTC, SergeyKukhtalevV commented on src/components/burger-constructor/burger-constructor.jsx
> +        authorization: 'c362a370-694e-40e1-b195-d72fbbfd69f7',
Авторизацию убрал, но `'сontent-Type'` оставил. Без него от сервера возвращается ошибка 400

2023-01-11 03:26 UTC, SergeyKukhtalevV commented on src/components/app/app.tsx
> +const urlApi = 'https://norma.nomoreparties.space/api/ingredients';
Ок

2023-01-11 03:29 UTC, SergeyKukhtalevV commented on src/components/app/app.tsx
> +  //const [ingredientsInfo, setIngredientsInfo] = useState({});
Ок

2023-01-11 03:33 UTC, SergeyKukhtalevV commented on src/components/burger-constructor/burger-constructor.jsx
> +    orderData: {},
Понял, спасибо!

2023-01-11 03:36 UTC, SergeyKukhtalevV commented on src/components/burger-constructor/burger-constructor.jsx
> +            className="text text_type_digits-medium">{state.reduce((total, i) => total + i.price, 0) + bun[0].price * 2}</p>
Ок.

2023-01-11 03:51 UTC, SergeyKukhtalevV commented on src/components/burger-constructor/burger-constructor.jsx
> +          setOrderNumber(order.orderData.order.number)
Поправил несколько иначе, при рефакторинге первого замечания. Взгляните, пожалуйста, так ок?

2023-01-11 08:29 UTC, randomroot approved these changes
🟡 **Работа принята с комментариями**

**Здравствуйте!**

Вы успешно внесли необходимые изменения и улучшения в ваш проект, однако остались несколько моментов, указанные в комментариях, на которые следует обратить внимание и учесть при разработке в следующих спринтах.

Тем не менее, на данном этапе работа принимается автоматически на второй итерации, поэтому ваш PR можно сливать в ветку `main`.

**Желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-01-11 08:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    document.querySelector('.buttonOrder').addEventListener('click', getOrder);
🔴 **Нужно исправить:**

Такой подход не следует применять в рамках React приложений, работа с реальным DOM осуществляется только в крайних случаях. Вызов функции `getOrder` следует перенести в `onClick` кнопки, а на время, пока у вас нет нужного номера заказа - отображать лоадер/текст о загрузке/пустое поле.

2023-01-11 08:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        console.log(data.order.number);
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2023-01-11 08:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        setOrderNumber(data.order.number);
🟡 **Можно улучшить:**

В целом данное значение вы можете получить из переменной `order`, необязательно выделять его в отдельный стейт :)

2023-01-11 08:29 UTC, randomroot commented on src/constants/constants.js
> +export const urlApi = 'https://norma.nomoreparties.space/api';
🔴 **Нужно исправить:**

Наименования всех констант (функции не в счёт), расположенных вне компонентов или функций, следует привести к стилю `UPPER_CASE`. Исключения составляют только переменные значение которых описывают `PropTypes`.

2023-01-11 17:49 UTC, SergeyKukhtalevV commented on src/constants/constants.js
> +export const urlApi = 'https://norma.nomoreparties.space/api';
Спасибо, поправил

2023-01-12 07:10 UTC, SergeyKukhtalevV commented on src/components/burger-constructor/burger-constructor.jsx
> +    document.querySelector('.buttonOrder').addEventListener('click', getOrder);
Готово

2023-01-12 07:10 UTC, SergeyKukhtalevV commented on src/components/burger-constructor/burger-constructor.jsx
> +        console.log(data.order.number);
Ок

2023-01-12 19:30 UTC, merged