Month9/step1
SergeyKukhtalevV/react-burger pull request #5
Opened 2023-03-11 06:26 UTC by SergeyKukhtalevV

Добрый день!

Прошу проверить!

2023-03-11 07:21 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/XEIC8sDTB5jwlQ> - что-то не работает перенаправление пользователя через 3 секунды, также вам нужно проверять поле на пустоту (используйте пропс `required`);

- <https://disk.yandex.com/i/lYltFCS-hSM1cQ> - изначально, кнопок быть не должно, вы должны показывать кнопки, если пользователь что-то изменил в своих данных;

- <https://disk.yandex.com/i/RFopJojk6DREww> - Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали).

  В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива. И вы должны посылать в запрос, актуальный список ингредиентов (которые в `burger-constructor`), а не все ингредиенты;

- При перезагрузке страницы, авторизированный пользователь, должен автоматически логинится, если не истёк токен. И если пользователь залогинен, и он перезагружает страницу на роуте `/profile`, то он также должен туда попасть, после перезагрузки страницы. Также, напоминаю, по чек-листу: Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;

- Вы должны вешать обработчик на событие onSubmit элемента form, а не на кнопку;

- <https://disk.yandex.com/i/dwb9DB_F67vwoQ> - при открытии/закрытии модального окна ингредиента, у вас каждый раз происходит запрос ингредиентов. Этого делать не нужно, лучше 1 раз при входе на страницу делать запрос и всё. Также не забудьте после исправления проверить работу модального окна (если открыть его на новой странице);

- По чек-листу: При клике на «История заказов» происходит переход на экран /profile/orders, ссылка «История заказов» становится активной, экран /profile/orders пока отображается пустым.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-11 07:21 UTC, ArslanDev666 commented on src/pages/forgot-password.jsx
> +                    onClick={forgotPassword}>Восстановить</Button>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-11 07:21 UTC, ArslanDev666 commented on src/pages/login.jsx
> +                    onClick={login}>Войти</Button>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-11 07:21 UTC, ArslanDev666 commented on src/pages/profile.jsx
> +            >Сохранить</Button>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-11 07:21 UTC, ArslanDev666 commented on src/pages/register.jsx
> +                    onClick={register}>Зарегистрироваться</Button>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-11 07:21 UTC, ArslanDev666 commented on src/pages/reset-password.jsx
> +                  onClick={resetPassword}>Сохранить</Button>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-11 07:21 UTC, ArslanDev666 commented on src/services/api.js
> +export const getUserInfoRequest = async (data) => {
**Надо исправить:**

Здесь и далее. Там, где вы передаёте токен в запрос. 

Вы должны делать проверку на истечение токена, если токен истёк, вы должны получить новый, и снова сделать запрос.

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-03-12 21:44 UTC, SergeyKukhtalevV commented on src/pages/forgot-password.jsx
> +                    onClick={forgotPassword}>Восстановить</Button>
Готово

2023-03-12 21:44 UTC, SergeyKukhtalevV commented on src/pages/login.jsx
> +                    onClick={login}>Войти</Button>
Готово

2023-03-12 21:44 UTC, SergeyKukhtalevV commented on src/pages/profile.jsx
> +            >Сохранить</Button>
Готово

2023-03-12 21:44 UTC, SergeyKukhtalevV commented on src/pages/register.jsx
> +                    onClick={register}>Зарегистрироваться</Button>
Готово

2023-03-12 21:45 UTC, SergeyKukhtalevV commented on src/pages/reset-password.jsx
> +                  onClick={resetPassword}>Сохранить</Button>
Готово

2023-03-14 14:17 UTC, SergeyKukhtalevV commented on src/services/api.js
> +export const getUserInfoRequest = async (data) => {
Ок, спасибо!

2023-03-14 14:17 UTC, SergeyKukhtalevV commented
Прошу повторно проверить.

2023-03-15 10:20 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но ещё осталось несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/XEIC8sDTB5jwlQ> - всё ещё не работает перенаправление, дал комментарии в коде по этому поводу;

- <https://disk.yandex.com/i/2ntlQDoV4jEICg> - немного поехала вёрстка, а также, в запросе `/orders` нужно чтобы id у булок были в начале и в конце массива;

- Советую походить по приложению с открытой консолью, у вас есть небольшое количество ошибок связанных с пропсами, не стал их сейчас затрагивать, т.к. вы скоро перейдёте на typescript, и там они наглядно будут отображаться.

2023-03-15 10:20 UTC, ArslanDev666 commented on src/pages/forgot-password.jsx
> +  );
**Надо исправить:**

Тут лучше не использовать `useCallback`, пользы от него тут не будет, т.к. обработчик событий используется только в одном элементе. А также, из-за того что в зависимостях у `useCallback` нету стейта, то объект `form`, всегда будет с пустым `email`.

2023-03-15 10:20 UTC, ArslanMustafin commented on src/pages/forgot-password.jsx
> +  }, [dispatch]);
**Надо исправить:**

У вас не работает перенаправление, т.к. у вас в зависимостях нету `userInfoAnswer`, поэтому `useEffect` и не срабатывает, когда значение меняется.

2023-03-15 10:20 UTC, ArslanDev666 commented on src/pages/forgot-password.jsx
> +  const [form, setValue] = useState({email: ''});
**Надо исправить:**

Лучше сменить название на `[formValues, setFormValues]`. А также вынести начальный стейт за пределы компонента.

```js
const initialFormState = {
  email: ''
}

const ForgotPasswordPage = () => {
  const [formValues, setFormValues] = useState(initialFormState);
  ...
}
```

2023-03-16 06:19 UTC, SergeyKukhtalevV commented on src/pages/forgot-password.jsx
> +  );
Спасибо!

2023-03-16 06:19 UTC, SergeyKukhtalevV commented on src/pages/forgot-password.jsx
> +  }, [dispatch]);
Да, пропустил

2023-03-16 06:22 UTC, SergeyKukhtalevV commented on src/pages/forgot-password.jsx
> +  const [form, setValue] = useState({email: ''});
Ок

2023-03-16 08:36 UTC, SergeyKukhtalevV commented
Учел ошибки, посмотрите, пожалуйста, еще раз.

2023-03-16 09:39 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-03-16 18:47 UTC, merged