Month9/step2
SergeyKukhtalevV/react-burger pull request #6
Opened 2023-03-22 16:01 UTC by SergeyKukhtalevV

Добрый вечер!

Прошу проверить!

2023-03-22 18:14 UTC, andryxxa93 requested changes
Доброго времени суток! Прошу исправить 😊 
Что понравилось:
- Реализовали раздельное хранение данных полученных по разным сокетам
- Хорошая работа с датами заказов
- Сокеты настроены и работают верно

Что необходимо исправить:
- Сокеты должны закрываться при уходе со страниц "Лента заказов" и "История заказов", сейчас судя по экшенам сокет остается открытым.
- Если авторизоваться и перейти на страницу "Истории заказов", то список заказов не подгружается. Если посмотреть на экшены, то сокеты как будто закрываются 

https://user-images.githubusercontent.com/60173362/226997552-13c83147-5ecb-4345-a084-693609c3720d.mov

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-22 18:14 UTC, andryxxa93 commented on src/components/app/app.tsx
> +        <Route path="/feed" element={<FeedOrdersPage isActive={modalFeedOrderActive}
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-22 18:14 UTC, andryxxa93 commented on src/components/app/app.tsx
>          <Route path="/ingredients/:id"
**Можно лучше**
Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Пожалуйста, посоветуйтесь с наставником.

2023-03-22 18:14 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      {/*<div className={`${modalStyles.modal__content}`} onClick={e => e.stopPropagation()}>*/}
**Можно улучшить**
Ненужный код лучше удалять

2023-03-22 18:14 UTC, andryxxa93 commented on src/components/order-info/OrderInfo.jsx
> +  const {wsConnected} = useSelector(store => store.feed);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-22 18:14 UTC, andryxxa93 commented on src/services/middleware/socketMiddleware.js
> +        socket.onmessage = event => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-03-25 14:41 UTC, SergeyKukhtalevV commented
Добрый день!
Поправил обязательные замечания.
Необязательные замечания поправлю на неделе каникул.

Спасибо за ревью!

2023-03-26 07:58 UTC, andryxxa93 commented
- Если зайти на страницу "История заказов", открыть какой-то заказ и потом закрыть, то пропадают цены заказов. 

https://user-images.githubusercontent.com/60173362/227762647-2b614206-90da-4edf-8cdc-dec0e02fe27d.mov

Дело в useEffect внутри `OrderCard` - попробуйте разбить его на несколько useEffect.

2023-03-26 08:11 UTC, SergeyKukhtalevV commented
Спасибо, разбил. Проверил, работает, как нужно.

2023-03-26 19:00 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-06 18:13 UTC, merged